spring:
  liquibase:
    enabled: true
    contexts: test

elysium:
  brands:
    kafka:
      topics:
        brand-changes: test-elysium-brands-v1
        organisation-changes: test-elysium-organisation-v1

security:
  oauth2:
    client:
      client-id: zeus
      client-secret: secret
      access-token-uri: http://zeus/oauth/token
      client-registration-id: brands
